#database settings
database:
  driver: postgres
  host: db-marketplace.klikdokter-stg.int
  port: 5432
  username: marketplace_user
  password: 
  dbname: marketplace
  schemaname: public
  logger:
    level: error #silent, error, warn, info
    slow-threshold: 200 #Slow SQL threshold
    ignore-not-found: true #Ignore ErrRecordNotFound error for logger

redis-database:
  host: localhost
  port: 6379
  password: redis
  is-use: true
  index:
  default-expiry:

kafka:
  bootstrap-servers: 172.22.199.109:9092
  prefix-topic: local-mp
  auto-offset: beginning
  max-pool-interval: 600000

url:
  baseurl: /v3/marketplace/
  baseprefix: /v3/marketplace/
  base-image-url: https://s3-v2-marketplace.s3.ap-southeast-1.amazonaws.com/m0cha-Goh1ahz1ti/

server:
  port: 5700
  env: dev
  log:
    level: info #debug, info, warn, error.
    output: console
    file-path: ./kd-microservice.log

elastic:
  host: http://elasticsearch-marketplace.klikdokter-stg.int:9200
  username: marketplace_api
  password: ooh9enoy4tieJaiz1Fei
  index:
    index-product-autocomplete : product
    index-merchant : merchant
    index-product-store : staging-2023-product-store
    index-merchants : staging-merchants
    index-merchants-zone : staging-merchants-zone
    index-category-store : staging-category-store
    index-category-tree : staging-category-tree
    index-brands : staging-brands
    index-cities : staging-cities
    index-order : staging-order
    index-order-draft : staging-order-draft
    index-order-history : staging-order-history
    index-fds-blacklist: fds-blacklist
    index-fds-rule: fds-rule
    index-wishlist : staging-wishlist
    index-payment-method : staging-payment-method
    index-discussions : discussions
    index-discussions-merchant : discussions-merchant
    index-events-reguler : staging-events-reguler
    index-events-special : staging-events-special
    index-events-category : staging-events-category
    index-location : staging-location
    index-banners : staging-banners
    index-merchant-product-rating-summary : staging-merchant-product-rating-summary
    index-voucher : staging-sales-voucher
    index-provinces : staging-provinces
    index-districts : staging-districts
    index-subdistricts : staging-subdistricts
    index-postalcodes : staging-postalcodes

security:
  jwt:
    key: abcdefgh1234
    skip-validation: false
    ttl: 86400 # in seconds
    refresh-ttl: 2592000 # in seconds
    cache-login-ttl: 43200 # in minutes
  firebase:
    salt: P@ssw0rdnyaJ4ncUk
    iteration: 20000
    key-len: 30

kalcare-api:
  server: https://kd-api.medkomtek-stg.com/mp/v3
  endpoint-auth: /auth/cms
  endpoint-queue: /temp-order-status-queue
  endpoint-webhook: /registered-webhook
  user-cred:
  pass-cred:
  client-id: "client.cms-mocha-stg.backoffice"
  cancel-hours: 0
  cancel-minutes: 1
  post-interval: 2
  post-minutes: 5

micro-service:
  base-url: https://api.medkomtek.net/eks-micro-service
  api-key: TUfDhxqRXRV6cyAmvrSj9q2GCdTMrPKPgFTSvQ7VUB8UBZ3LzJ
  sms-path-url: /queue/job

icons:
  info: "https://s3-publishing-cmn-svc-prd.s3.ap-southeast-1.amazonaws.com/assets/icon/klikmedis/notification/lonceng.svg"
  chat: "https://s3-publishing-cmn-svc-prd.s3.ap-southeast-1.amazonaws.com/assets/icon/klikmedis/notification/chat.svg"
  video-call: "https://s3-publishing-cmn-svc-prd.s3.ap-southeast-1.amazonaws.com/assets/icon/klikmedis/notification/video-call.svg"
