basePath: /marketplace-svc/api/v1/
consumes:
    - application/json
definitions:
    BodyMerchantProduct:
        properties:
            apotek_uid:
                type: string
                x-go-name: ApotekUID
            items:
                items:
                    $ref: '#/definitions/BodyReceiptsItems'
                type: array
                x-go-name: Items
            lat:
                format: double
                type: number
                x-go-name: Lat
            lon:
                format: double
                type: number
                x-go-name: Lon
        type: object
        x-go-package: marketplace-svc/app/model/request/elastic
    BodyReceiptsItems:
        properties:
            qty:
                format: int64
                type: integer
                x-go-name: QTY
            sku:
                type: string
                x-go-name: SKU
        type: object
        x-go-package: marketplace-svc/app/model/request/elastic
    MerchantProductItems:
        properties:
            image:
                type: string
                x-go-name: Image
            is_available:
                type: boolean
                x-go-name: IsAvailable
            merchant_sku:
                type: string
                x-go-name: MerchantSKU
            name:
                type: string
                x-go-name: Name
            qty:
                format: int64
                type: integer
                x-go-name: QTY
            qty_available:
                format: double
                type: number
                x-go-name: QTYAvailable
            selling_price:
                format: double
                type: number
                x-go-name: SellingPrice
            sku:
                type: string
                x-go-name: SKU
            special_price:
                format: double
                type: number
                x-go-name: SpecialPrice
            status:
                type: string
                x-go-name: Status
            total_price:
                format: double
                type: number
                x-go-name: TotalPrice
            uom:
                type: string
                x-go-name: UOM
            uom_name:
                type: string
                x-go-name: UOMName
        type: object
        x-go-package: marketplace-svc/app/model/response/elastic
    MerchantProductResponse:
        properties:
            available_items:
                format: int64
                type: integer
                x-go-name: AvailableItems
            distance:
                format: double
                type: number
                x-go-name: Distance
            id:
                format: double
                type: number
                x-go-name: ID
            items:
                items:
                    $ref: '#/definitions/MerchantProductItems'
                type: array
                x-go-name: Items
            name:
                type: string
                x-go-name: Name
            shippings:
                items: {}
                type: array
                x-go-name: Shippings
            total_items:
                format: int64
                type: integer
                x-go-name: TotalItems
            total_price:
                format: double
                type: number
                x-go-name: TotalPrice
            type:
                type: string
                x-go-name: Type
            uid:
                type: string
                x-go-name: UID
        type: object
        x-go-package: marketplace-svc/app/model/response/elastic
    MetaResponse:
        properties:
            code:
                description: Code is the response code
                example: 1000
                format: int64
                type: integer
                x-go-name: Code
            correlation_id:
                description: |-
                    CorrelationId is the response correlation_id
                    in: string
                type: string
                x-go-name: CorrelationId
            message:
                description: Message is the response message
                example: Success
                type: string
                x-go-name: Message
            pagination:
                $ref: '#/definitions/PaginationResponse'
        type: object
        x-go-package: marketplace-svc/app/model/base
    PaginationResponse:
        properties:
            limit:
                format: int64
                type: integer
                x-go-name: Limit
            page:
                format: int64
                type: integer
                x-go-name: Page
            records:
                format: int64
                type: integer
                x-go-name: Records
            total_page:
                format: int64
                type: integer
                x-go-name: TotalPage
            total_records:
                format: int64
                type: integer
                x-go-name: TotalRecords
        type: object
        x-go-name: Pagination
        x-go-package: marketplace-svc/app/model/base
    PharmaciesResponse:
        properties:
            code:
                type: string
                x-go-name: Code
            name:
                type: string
                x-go-name: Name
            uid:
                type: string
                x-go-name: UID
        type: object
        x-go-package: marketplace-svc/app/model/response/elastic
    ProductResponse:
        properties:
            description:
                type: string
                x-go-name: Description
            image:
                type: string
                x-go-name: Image
            min_price:
                type: string
                x-go-name: MinPrice
            pharmacy_code:
                type: string
                x-go-name: PharmacyCode
            price:
                type: string
                x-go-name: Price
            principal_name:
                type: string
                x-go-name: PrincipalName
            prod_code:
                type: string
                x-go-name: ProdCode
            prod_name:
                type: string
                x-go-name: ProdName
            proportional:
                type: string
                x-go-name: Proportional
            short_description:
                type: string
                x-go-name: ShortDescription
            uom:
                type: string
                x-go-name: UOM
            uom_name:
                type: string
                x-go-name: UOMName
            weight:
                type: string
                x-go-name: Weight
        type: object
        x-go-package: marketplace-svc/app/model/response/elastic
    SuccessResponse:
        properties:
            data:
                $ref: '#/definitions/data'
            errors:
                description: |-
                    Errors is the response message
                    in: interface
                x-go-name: Errors
            meta:
                $ref: '#/definitions/MetaResponse'
        type: object
        x-go-name: responseHttp
        x-go-package: marketplace-svc/app/model/base
    data:
        properties:
            record:
                x-go-name: Record
            records:
                x-go-name: Records
        type: object
        x-go-package: marketplace-svc/app/model/base
info:
    title: 'Marketplace Service:'
    version: "0.1"
paths:
    /merchant-product:
        post:
            description: Merchant - List
            operationId: MerchantProductRequest
            parameters:
                - description: Additional Fields
                  example: '"description,short_description"'
                  in: query
                  name: fields
                  type: string
                  x-go-name: Fields
                - description: StoreID
                  format: int64
                  in: query
                  name: store_id
                  type: integer
                  x-go-name: StoreID
                - description: Page number
                  format: int64
                  in: query
                  name: page
                  type: integer
                  x-go-name: Page
                - description: Maximum records per page
                  format: int64
                  in: query
                  name: limit
                  type: integer
                  x-go-name: Limit
                - description: Field to be sorted
                  in: query
                  name: Sort
                  type: string
                - $ref: '#/definitions/BodyMerchantProduct'
                  in: query
                  name: body
                  x-go-name: Body
            responses:
                "200":
                    description: Merchant - List success response
                    schema:
                        properties:
                            data:
                                properties:
                                    records:
                                        items:
                                            $ref: '#/definitions/MerchantProductResponse'
                                        type: array
                                type: object
                            meta:
                                $ref: '#/definitions/MetaResponse'
            security:
                - Bearer: []
            tags:
                - Merchants
    /pharmacies:
        get:
            description: Pharmacies - List
            operationId: PharmaciesRequest
            parameters:
                - description: Global Search
                  in: query
                  name: q
                  type: string
                  x-go-name: Query
                - in: query
                  name: fields
                  type: string
                  x-go-name: Fields
                - format: int64
                  in: query
                  name: store_id
                  type: integer
                  x-go-name: StoreID
                - in: query
                  name: store
                  type: string
                  x-go-name: Store
                - in: query
                  name: sort
                  type: string
                  x-go-name: Sort
                - in: query
                  name: dir
                  type: string
                  x-go-name: Dir
                - format: int64
                  in: query
                  name: page
                  type: integer
                  x-go-name: Page
                - format: int64
                  in: query
                  name: limit
                  type: integer
                  x-go-name: Limit
            responses:
                "200":
                    description: Pharmacies - List success response
                    schema:
                        properties:
                            data:
                                properties:
                                    records:
                                        items:
                                            $ref: '#/definitions/PharmaciesResponse'
                                        type: array
                                type: object
                            meta:
                                $ref: '#/definitions/MetaResponse'
            security:
                - Bearer: []
            tags:
                - Merchants
    /products:
        get:
            description: Product - List
            operationId: ProductRequest
            parameters:
                - description: Global Search
                  in: query
                  name: q
                  type: string
                  x-go-name: Query
                - description: Additional Fields
                  example: '"description,short_description"'
                  in: query
                  name: fields
                  type: string
                  x-go-name: Fields
                - description: StoreID
                  format: int64
                  in: query
                  name: store_id
                  type: integer
                  x-go-name: StoreID
                - description: Page number
                  format: int64
                  in: query
                  name: page
                  type: integer
                  x-go-name: Page
                - description: Maximum records per page
                  format: int64
                  in: query
                  name: limit
                  type: integer
                  x-go-name: Limit
                - description: |-
                    JSON value for filtering. The format is {"field_name": "filter_keyword", ...}
                    Example {"name":"Dr Ican","str_no":"XXXX-XXXX"]}
                  in: query
                  name: Filter
                  type: string
            responses:
                "200":
                    description: Product - List success response
                    schema:
                        properties:
                            data:
                                properties:
                                    records:
                                        items:
                                            $ref: '#/definitions/ProductResponse'
                                        type: array
                                type: object
                            meta:
                                $ref: '#/definitions/MetaResponse'
            security:
                - Bearer: []
            tags:
                - Products
produces:
    - application/json
responses:
    ErrorResponseBody:
        description: ""
        schema:
            properties:
                data:
                    type: object
                    x-go-name: Data
                errors:
                    properties:
                        field_name:
                            type: string
                            x-go-name: FieldName
                    type: object
                    x-go-name: Errors
                meta:
                    $ref: '#/definitions/MetaResponse'
            type: object
schemes:
    - https
securityDefinitions:
    Bearer:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
