package entity

import "time"

type ProductFlat struct {
	ID                      int       `json:"id"`
	Name                    string    `json:"name"`
	Sku                     string    `json:"sku"`
	Slug                    string    `json:"slug"`
	Barcode                 string    `json:"barcode"`
	BrandCode               string    `json:"brand_code"`
	PrincipalCode           any       `json:"principal_code"`
	ProductGroupID          int       `json:"product_group_id"`
	MetaTitle               string    `json:"meta_title"`
	MetaDescription         string    `json:"meta_description"`
	MetaKeyword             string    `json:"meta_keyword"`
	Description             string    `json:"description"`
	ShortDescription        string    `json:"short_description"`
	Weight                  float64   `json:"weight"`
	BasePoint               int       `json:"base_point"`
	BasePointRupiah         float64   `json:"base_point_rupiah"`
	AttributeSetID          int       `json:"attribute_set_id"`
	TypeID                  string    `json:"type_id"`
	Status                  int       `json:"status"`
	DeletedAt               any       `json:"deleted_at"`
	Length                  float64   `json:"length"`
	Height                  float64   `json:"height"`
	Width                   float64   `json:"width"`
	MetaTitleH1             string    `json:"meta_title_h1"`
	CustomerGroupID         int       `json:"customer_group_id"`
	TaxClassID              string    `json:"tax_class_id"`
	BasePrice               float64   `json:"base_price"`
	FinalPrice              any       `json:"final_price"`
	MinPrice                float64   `json:"min_price"`
	MaxPrice                float64   `json:"max_price"`
	TierPrice               any       `json:"tier_price"`
	GroupPrice              any       `json:"group_price"`
	SpecialPrice            any       `json:"special_price"`
	SpecialFromDate         any       `json:"special_from_date"`
	SpecialToDate           any       `json:"special_to_date"`
	StoreID                 int       `json:"store_id"`
	CategoryIds             any       `json:"category_ids"`
	UpperLimitPrice         any       `json:"upper_limit_price"`
	Images                  string    `json:"images"`
	MaximumPurchaseQuantity string    `json:"maximum_purchase_quantity"`
	ProductMetaDescription  string    `json:"product_meta_description"`
	Visibility              string    `json:"visibility"`
	ManagementFee           string    `json:"management_fee"`
	IsFreeProduct           int       `json:"is_free_product"`
	Preorder                int       `json:"preorder"`
	ProductKn               int       `json:"product_kn"`
	ProductKalbe            int       `json:"product_kalbe"`
	IsSpot                  int       `json:"is_spot"`
	IsActive                int       `json:"is_active"`
	Saleable                int       `json:"saleable"`
	RewardPointSellProduct  string    `json:"reward_point_sell_product"`
	EpmPrice                float64   `json:"epm_price"`
	ProductMetaTitle        string    `json:"product_meta_title"`
	ProductSlug             string    `json:"product_slug"`
	CbpPrice                float64   `json:"cbp_price"`
	IsFamilyGift            int       `json:"is_family_gift"`
	IsLangganan             int       `json:"is_langganan"`
	IsTicket                int       `json:"is_ticket"`
	EpmSku                  string    `json:"epm_sku"`
	NewsFromDate            any       `json:"news_from_date"`
	NewsToDate              any       `json:"news_to_date"`
	ProductDescription      string    `json:"product_description"`
	IsKliknow               int       `json:"is_kliknow"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
}
