package base

const (
	// PAGINATION
	PAGINATION_MAX_LIMIT = 100
	PAGINATION_MIN_LIMIT = 10

	// QUEUE
	TOPIC_ORDER_CREATE_NOTIFIY = "order-create-notify"
	TOPIC_ORDER_STATUS         = "order-status"
	TOPIC_CATALOG_PRODUCT      = "catalog-product"
	TOPIC_CATALOG_PRODUCT_BIG  = "catalog-product-big"

	// ORDER_STATUS
	ORDER_STATUS_NONE      = 0
	ORDER_STATUS_DRAFT     = 1
	ORDER_STATUS_PENDING   = 3
	ORDER_STATUS_PROCEED   = 4
	ORDER_STATUS_SHIPPED   = 5
	ORDER_STATUS_HOLD      = 6
	ORDER_STATUS_DELIVERED = 7
	ORDER_STATUS_CONFIRMED = 8
	ORDER_STATUS_CLOSED    = 9
	ORDER_STATUS_CANCELED  = 10
	ORDER_STATUS_REFUND    = 11
)
